name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  app_api:
    path: ../../api
  authentication_client:
    path: ../authentication_client/authentication_client
  # deep_link_client:
  #   path: ../deep_link_client
  equatable: ^2.0.5
  package_info_client:
    path: ../package_info_client
  rxdart: ^0.27.7
  storage:
    path: ../storage/storage

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
