name: app_api
description: A Flutter api server app built with the dart_frog package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_frog: ^1.1.0
  equatable: ^2.0.5
  feed_blocks:
    path: packages/feed_blocks
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
