targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - cast_nullable_to_non_nullable
            - implicit_dynamic_parameter
            - lines_longer_than_80_chars
            - prefer_const_constructors
            - require_trailing_commas
      json_serializable:
        options:
          any_map: false
          checked: true
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: false
