name: feed_blocks
description: Reusable Feed Blocks for the Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.0.0
  mocktail: ^1.0.2
  test: ^1.25.2
  very_good_analysis: ^5.1.0
