name: feed_blocks
description: Reusable Feed Blocks for the Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.9
  coverage: ^1.7.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0
