#!/bin/sh

# flutter clean && flutter pub get && flutter pub upgrade && dart run build_runner build --delete-conflicting-outputs

flutter clean && flutter packages pub get && dart run build_runner build --delete-conflicting-outputs
