name: token_storage
description: Token storage for the authentication client.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.2 <4.0.0"

dev_dependencies:
  coverage: ^1.7.2
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0
